// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3467.Robot2015.subsystems;

import org.usfirst.frc3467.Robot2015.OI;
import org.usfirst.frc3467.Robot2015.RobotMap;
import org.usfirst.frc3467.Robot2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
@SuppressWarnings("unused")
public class DriveBase extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static SpeedController speedController1 = RobotMap.driveBaseSpeedController1;
    static SpeedController speedController2 = RobotMap.driveBaseSpeedController2;
    static SpeedController speedController3 = RobotMap.driveBaseSpeedController3;
    static SpeedController speedController4 = RobotMap.driveBaseSpeedController4;
    static RobotDrive robotDrive41 = RobotMap.driveBaseRobotDrive41;
    static Gyro gyro1 = RobotMap.driveBaseGyro1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public static void driveRobotOrientedMecanumJames(){
   	 RobotMap.driveBaseRobotDrive41.mecanumDrive_Cartesian(-((OI.stick1.getX())+(OI.stick2.getX()))/2,
   			 											((OI.stick1.getY())+(OI.stick2.getY()))/2,
   			 											OI.stick1.getY()-OI.stick2.getY(),
   			 											0 );
   	 //uses joystick 1 X and Y for x and y movement and joystick 2 x for rotation
   }
   public static void driveRobotOrientedMecanum(){
   	RobotMap.driveBaseRobotDrive41.mecanumDrive_Cartesian(-(OI.stick1.getX()), (OI.stick1.getY()), (OI.stick1.getZ())*Math.abs((OI.stick1.getZ())) / (2), 0 );
   	//at this point this is the equivalent of driveRobotOrientedmMecanum, code to get gyro angle is not in place
   }
   public static void driveFieldOrientedMecanum(){
	   	RobotMap.driveBaseRobotDrive41.mecanumDrive_Cartesian(-(OI.stick1.getX()), (OI.stick1.getY()), (OI.stick1.getZ())*Math.abs((OI.stick1.getZ())) / (2), -(gyro1.getAngle()) );
	   	//at this point this is the equivalent of driveRobotOrientedmMecanum, code to get gyro angle is not in place
   }
  
    public static void turnToAngle(int Angle){
	  while(Math.abs((((gyro1.getAngle()%360)+360)%360 - Angle)) > 5){
		  robotDrive41.drive(1, 0);
	  }
	  while(Math.abs((((gyro1.getAngle()%360)+360)%360 - Angle)) > 2){
		  robotDrive41.drive(-0.5, 0);
	  }
		   speedController1.set(0);
		   speedController2.set(0);
		   speedController3.set(0);
		   speedController4.set(0);
   } 
public static void driveStraight() {
	RobotMap.driveBaseRobotDrive41.drive(-1.0, gyro1.getAngle() * -360);
	
}

	}

